### ISSUE TITLE
Point the SessionStore to the required database schema

### ISSUE THREAD

**Issue by madhav-vl** [mweibel/connect-session-sequelize#113]
Hi, I have multiple schemas (db1, db2, db3, etc.) created in my Postgres database apart from the default schema public.
Sequelize session store always pointing the default set database schema (public). Is there any config parameter that allows changing database schema. Code provided below for reference.

```
import session from 'express-session';
const SequelizeStore = require("connect-session-sequelize")(session.Store);

var app = express();
app.use(
  session({
    secret: "secretcode",
    store: new SequelizeStore({
      db: sequelize,
      tableName: 'user_session',
      schema: 'db1' //need this kind of parameter to set db schema 
    }),
    resave: false,
    proxy: true,
  })
);
```

**Comment by mweibel** [comment]
Unless I'm mistaken, this is not really an issue of `connect-session-sequelize` as you pass in a `sequelize` connected db object which probably allows to specify a schema.
Otherwise you could try specifying the tableName using the schema, f.e. `db1.user_session`. Never tested this though. 

If you figure out how to do it - I'd gladly accept a docs update PR.
