### ISSUE TITLE
[Question] store.sync() function needed if I create the table myself?

### ISSUE THREAD

**Issue by geordidearns** [mweibel/connect-session-sequelize#121]
Hi there,

I just implemented this with express and saw the _store_.sync() method to create the table. I'm wondering what this function outside of this does? The word sync feels like it does something else but the documentation didn't help me find my answer so thought i'd ask here :) 

Couple of points that would be awesome to get clarified:
1. If i create these tables myself with the identical columns and types do I need this method?
2. If I do, what is the purpose of the fetching of indexes each time the server restarts? (Output posted below)

Thanks for your help, really appreciate it!

`SELECT i.relname AS name, ix.indisprimary AS primary, ix.indisunique AS unique, ix.indkey AS indkey, array_agg(a.attnum) as column_indexes, array_agg(a.attname) AS column_names, pg_get_indexdef(ix.indexrelid) AS definition FROM pg_class t, pg_class i, pg_index ix, pg_attribute a WHERE t.oid = ix.indrelid AND i.oid = ix.indexrelid AND a.attrelid = t.oid AND t.relkind = 'r' and t.relname = 'Session' GROUP BY i.relname, ix.indexrelid, ix.indisprimary, ix.indisunique, ix.indkey ORDER BY i.relname;`

**Comment by mweibel** [comment]
https://github.com/mweibel/connect-session-sequelize/blob/master/lib/connect-session-sequelize.js#L74

Calls [`sync()`](https://sequelize.org/master/class/lib/model.js~Model.html#static-method-sync) on the model. Hope this helps :) 

Feel free to send a PR to amend the README.

**Comment by geordidearns** [comment]
@mweibel Sorry for the follow up but i didn't understand exactly.. This only needs to be called once to create the table? Or what does the 'sync' do apart from that? Thanks for your time :)

**Comment by mweibel** [comment]
As you see in the linked code it calls `sync` on the model. Which, as linked as well does:
> Sync this Model to the DB, that is create the table.

If you want to know more, reading the documentation of sequelize (or the code) is due:
https://sequelize.org/master/manual/model-basics.html#model-synchronization

It proabably could be part of your deployment process instead of running it on starting the server. Then again why do you care much, node server restarts shouldn't happen that often that it bothers you (otherwise you might have different issues). 

It might be that sequelize requires a sync so it knows about the created tables and their states internally as well - here again I'd recommend you to go to sequelize and read up / ask.

**Comment by geordidearns** [comment]
@mweibel Thanks for that - I will take a look into it a bit more. Appreciate the response!
