### ISSUE TITLE
Confused between connect-session-sequelize and express-sequelize-session 

### ISSUE THREAD

**Issue by scf4** [mweibel/connect-session-sequelize#43]
They both seem to have a similar API, is one a fork of the other?

**Comment by jakeorr** [comment]
This is the first I've heard of express-sequelize-session. It doesn't appear to be a fork. From a quick look it looks like a newer entry into a similar space as this project.

**Comment by scf4** [comment]
Thanks. I was a little confused because it has more downloads and is the first NPM result for "connect-session-sequelize" on Google.

**Comment by mweibel** [comment]
Not sure why either, but maybe for some it's not clear that the `connect` prefix is because of historical reasons that the session module of express was originally connect-session (IIRC). 
Anyway, I wonder where you the more downloads from, when I look at the npm stats it seems that connect-session-sequelize has more downloads (though that number has to be taken with a grain of salt, as CI systems might download it all the time and therefore fake the numbers).
